resources:
  repositories:
  # The name used to reference this repository in the checkout step
  - repository: BashCalcRepo 
    type: github
    endpoint: TestGitHub
    name: n-grounds/bashCalc
  # The name used to reference this repository in the checkout step
  - repository: WindowsBatchRepo
    type: github
    endpoint: TestGitHub
    name: n-grounds/winBatch

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: CheckoutBothInParallel
  jobs:
  - job: windows
    pool:
      vmImage: 'windows-latest'
    steps:
    - checkout: WindowsBatchRepo
  - job: ubuntu
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: BashCalcRepo
