resources:
  repositories:
  # The name used to reference this repository in the checkout step
  - repository: BashCalcRepo 
    type: github
    endpoint: TestGitHub
    name: n-grounds/bashCalc
  # The name used to reference this repository in the checkout step
  - repository: WindowsBatchRepo
    type: github
    endpoint: TestGitHub
    name: n-grounds/winBatch

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: PreChecks
  jobs:
  - job: preflight
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: none
    - script: echo "Performing pre-flight checks"
      displayName: 'Pre-Log'
    - script: echo "All done checking pre-flight"
      displayName: "Post-Log"
- stage: CheckoutBothInParallel
  jobs:
  - job: windows
    pool:
      vmImage: 'windows-latest'
    steps:
    - checkout: WindowsBatchRepo
  - job: ubuntu
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: BashCalcRepo
